name: Deploy to GitHub pages branch
on:
  push:
    branches: ts
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false 
      - name: Use Node.js 15
        uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: Build
        run: |
          npm install
          mkdir -p dist
          npm run-script build
      - name: Prepare for deploy
        run: |
          rm -rf targetdir
          mkdir -p targetdir
          mv Pictures index.html Synergism.css favicon.ico targetdir/
      - name: Deploy with the $GME emoji for some reason ðŸš€
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: targetdir