name: Deploy to GitHub pages branch
on:
  push:
    branches: master
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false 
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install deps
        run: |
          npm install
      - name: Lint
        run: |
          npm run lint
          npm run csslint
      - name: Build
        run: |
          node ./scripts/update-last-updated.js
          npm run-script build:esbuild
      - name: Prepare for deploy
        run: |
          rm -rf targetdir
          mkdir -p targetdir
          mv dist Pictures index.html Synergism.css favicon.ico targetdir/
      - name: Deploy with the $GME emoji for some reason ðŸš€
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: targetdir
      - name: Copy files
        run: |
          rm -rf ./src
          mv targetdir src
      - name: Uploads files to Steam version
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'src'
          destination_repo: 'Pseudo-Corp/steam'
          destination_folder: '.'
          user_email: 'maitken033380023@gmail.com'
          user_name: 'KhafraDev'
          commit_message: 'Update Synergism'
